on:
  push:
    # paths:
    #   - patches/**
    #   - .github/workflows/patches.yml

jobs:
  checks:
    runs-on: ubuntu-latest
    name: apply patches
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws cli for s3 uploads
        run: |
          pip install awscli-plugin-endpoint

          mkdir ~/.aws
          cat > ~/.aws/config <<CONF
          [plugins]
          endpoint = awscli_plugin_endpoint

          [default]
          region = ${SCW_REGION}
          s3 =
            endpoint_url = https://s3.fr-par.scw.cloud
            signature_version = s3v4
          s3api =
            endpoint_url = https://s3.fr-par.scw.cloud
          CONF
          cat > ~/.aws/credentials <<CREDS
          [default]
          aws_access_key_id = ${{ secrets.SCW_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.SCW_SECRET_KEY }}
          CREDS

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_458
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-458.dsk.gz

      - name: apply 458
        if: steps.built_458.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 457
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/458 > /tmp/458.patch
            cd /
            patch -p0 < /tmp/458.patch
            cd /usr/src/bin/tcsh
            make
            make install
            make clean
            cd /sys/SIMH
            make
            make install
            cd /sys/GENERIC
            make
            cp unix /genunix

      - if: steps.built_458.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-458.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_459
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-459.dsk.gz

      - name: apply 459
        if: steps.built_459.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 458
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/459 > /tmp/459.sh
            cd /tmp
            sh 459.sh
            cd /
            patch -p0 < /tmp/459.patch
            install -c -m 444 -o root -g wheel /tmp/stdarg.h /usr/include
            rm /usr/include/vaxuba
            rm /usr/src/asm.sed*
            rm -r /usr/src/include

      - if: steps.built_459.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-459.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_460
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-460.dsk.gz

      - name: apply 460
        if: steps.built_460.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 459
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/460 > /tmp/460.sh
            cd /tmp
            sh 460.sh
            uudecode cpp.tar.Z.uu
            uncompress cpp.tar.Z
            cd /
            patch -p0 < /tmp/ccom.patch
            cd /usr/src/lib/ccom
            make
            make install
            cd /usr/src/bin
            make cc
            install -m 755 -o root -g wheel -s cc /bin
            cd /
            tar xf /tmp/cpp.tar
            cd /usr/src/lib/cpp
            make
            make install
            cd /
            patch -p0 < /tmp/src.patch

      - if: steps.built_460.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-460.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_461
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-461.dsk.gz

      - name: apply 461
        if: steps.built_461.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 460
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/461 > /tmp/461.patch
            cd /
            patch -p0 < /tmp/461.patch
            cd /usr/src/ucb/ex
            make
            make install
            make clean
            cd /sys/SIMH
            make
            make install
            cd /sys/GENERIC
            make
            cp unix /genunix

      - if: steps.built_461.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-461.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_462
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-462.dsk.gz

      - name: apply 462
        if: steps.built_462.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 461
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/462 > /tmp/462.patch
            cd /
            patch -p0 < /tmp/462.patch
            cd /usr/src/usr.bin/f77
            rm -rf malloc.c
            make
            make install
            make clean

      - if: steps.built_462.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-462.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_463
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-463.dsk.gz

      - name: apply 463
        if: steps.built_463.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 462
          run: |
            sed -e '1,/.*--- cut here---.*/ d' < patches/463 > /tmp/463.patch
            cd /
            patch -p0 < /tmp/463.patch
            cd /usr/src/ucb/rlogin
            make
            make install
            make clean
            cd /usr/src/ucb/sendbug
            make
            make install
            make clean
            cd /sys/SIMH
            make
            make install
            cd /sys/GENERIC
            make
            cp unix /genunix
            cd /usr/src/man/man3
            make sysctl.0
            install -c -o bin -g bin -m 444 sysctl.0 /usr/man/cat3
            rm sysctl.0

      - if: steps.built_463.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-463.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_464
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-464.dsk.gz

      - name: apply 464
        if: steps.built_464.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 463
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/464 > /tmp/464.patch
            cd /
            patch -p0 < /tmp/464.patch
            cd /sys/SIMH
            make
            make install
            cd /sys/GENERIC
            make
            cp unix /genunix

      - if: steps.built_464.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-464.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_465
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-465.dsk.gz

      - name: apply 465
        if: steps.built_465.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 464
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/465 > /tmp/465.sh
            cd /tmp
            sh 465.sh
            sh top.shar
            cd /
            patch -p0 < /tmp/465.patch
            cd /usr/src/lib/ccom
            make
            make install
            make clean
            cd /usr/src/ucb/top
            make
            make install
            make clean

      - if: steps.built_465.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-465.dsk.gz

####################################################################################################
      - name: check if build is needed
        continue-on-error: true
        id: built_466
        run: aws s3 ls s3://asjackson-211bsd-ci/211bsd-ci-466.dsk.gz

      - name: apply 466
        if: steps.built_466.outcome != 'success'
        uses: ./
        with:
          path: /github
          patch_level: 465
          run: |
            sed -e '1,/.*---cut here---.*/ d' < patches/466 > /tmp/466.patch
            cd /
            patch -p0 < /tmp/466.patch
            cd /usr/src/ucb/top
            make
            make install
            make clean
            cd /usr/src/bin
            make df size
            install -s -m 751 -g staff size /bin/size
            install -s -m 2751 -g operator df /bin/df
            make clean
            cd /usr/src/man/man1
            make df.0
            install -c -o bin -g bin -m 444 df.0 /usr/man/cat1
            make clean
            cd /usr/src/ucb/top
            make
            make install
            make clean

      - if: steps.built_466.outcome != 'success'
        run: |
          gzip ../ci.dsk
          aws s3 cp ../ci.dsk.gz s3://asjackson-211bsd-ci/211bsd-ci-466.dsk.gz
